# Generated by Django 4.1.7 on 2023-03-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0003_photo_title_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='create_at',
        ),
    ]
