# Generated by Django 4.1.7 on 2023-04-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0004_remove_photo_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
