# Generated by Django 4.1.7 on 2023-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0005_photo_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sub_count',
            field=models.IntegerField(default=0),
        ),
    ]
