# Generated by Django 4.1.7 on 2023-04-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0006_photo_sub_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='sub_count',
        ),
        migrations.AddField(
            model_name='user',
            name='sub_count',
            field=models.IntegerField(default=0),
        ),
    ]
