# Generated by Django 4.1.7 on 2023-04-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0007_remove_photo_sub_count_user_sub_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='time_creation',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
